# Regression Exercise 

California Housing Data

This data set contains information about all the block groups in California from the 1990 Census. In this sample a block group on average includes 1425.5 individuals living in a geographically compact area. 

The task is to aproximate the median house value of each block from the values of the rest of the variables. 

 It has been obtained from the LIACC repository. The original page where the data set can be found is: http://www.liaad.up.pt/~ltorgo/Regression/DataSets.html.
 
 
https://www.udemy.com/course/complete-guide-to-tensorflow-for-deep-learning-with-python/learn/lecture/7876662#overview

The Features:
 
* housingMedianAge: continuous. 
* totalRooms: continuous. 
* totalBedrooms: continuous. 
* population: continuous. 
* households: continuous. 
* medianIncome: continuous. 
* medianHouseValue: continuous. 

## The Data

** Import the cal_housing_clean.csv file with pandas. Separate it into a training (70%) and testing set(30%).**

In [17]:
import pandas as pd
import tensorflow as tf
import matplotlib as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
%matplotlib inline

In [18]:
pd_data = pd.read_csv("cal_housing_clean.csv")

In [67]:
pd_data.describe().transpose()

count           mean            std         min  \
housingMedianAge  20640.0      28.639486      12.585558      1.0000   
totalRooms        20640.0    2635.763081    2181.615252      2.0000   
totalBedrooms     20640.0     537.898014     421.247906      1.0000   
population        20640.0    1425.476744    1132.462122      3.0000   
households        20640.0     499.539680     382.329753      1.0000   
medianIncome      20640.0       3.870671       1.899822      0.4999   
medianHouseValue  20640.0  206855.816909  115395.615874  14999.0000   

                          25%          50%           75%          max  
housingMedianAge      18.0000      29.0000      37.00000      52.0000  
totalRooms          1447.7500    2127.0000    3148.00000   39320.0000  
totalBedrooms        295.0000     435.0000     647.00000    6445.0000  
population           787.0000    1166.0000    1725.00000   35682.0000  
households           280.0000     409.0000     605.00000    6082.0000  
medianIncome           2.5634       3.5348       4.74325      15.0001  
medianHouseValue  119600.0000  179700.0000  264725.00000  500001.0000

In [20]:
y_val = pd_data['medianHouseValue']
x_data = pd_data.drop('medianHouseValue', axis=1)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_val, test_size=0.3, random_state=101)

### Scale the Feature Data

** Use sklearn preprocessing to create a MinMaxScaler for the feature data. Fit this scaler only to the training data. Then use it to transform X_test and X_train. Then use the scaled X_test and X_train along with pd.Dataframe to re-create two dataframes of scaled data.**

In [22]:
scaler = MinMaxScaler()

In [23]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [25]:
X_train = pd.DataFrame(data=scaler.transform(X_train),
                      columns=X_train.columns,
                      index=X_train.index)

In [26]:
X_test = pd.DataFrame(data=scaler.transform(X_test),
                      columns=X_test.columns,
                      index=X_test.index)

In [29]:
#

### Create Feature Columns

** Create the necessary tf.feature_column objects for the estimator. They should all be trated as continuous numeric_columns. **

In [44]:
cols = x_data.columns

Index(['housingMedianAge', 'totalRooms', 'totalBedrooms', 'population',
       'households', 'medianIncome'],
      dtype='object')

In [45]:
tf_fs = dict(zip([i for i in cols], [tf.feature_column.numeric_column(i) for i in cols]))

In [46]:
feat_cols = [i for i in tf_fs.values()]
feat_cols

[NumericColumn(key='housingMedianAge', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='totalRooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='totalBedrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='population', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='households', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='medianIncome', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

** Create the input function for the estimator object. (play around with batch_size and num_epochs)**

In [47]:
input_func = tf.estimator.inputs.pandas_input_fn(x = X_train,
                                                y = y_train,
                                                batch_size = 10,
                                                num_epochs = 1000,
                                                shuffle = True)

** Create the estimator model. Use a DNNRegressor. Play around with the hidden units! **

In [48]:
model = tf.estimator.DNNRegressor(hidden_units=[6,6,6,6], feature_columns=feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\Tzeentch\\AppData\\Local\\Temp\\tmprwo_xlwq', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001E3BFBB5278>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


##### ** Train the model for ~1,000 steps. (Later come back to this and train it for more and check for improvement) **

In [49]:
model.train(input_fn=input_func, steps=1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\Tzeentch\AppData\Local\Temp\tmprwo_xlwq\model.ckpt.
INFO:tensorflow:loss = 421888360000.0, step = 1
INFO:tensorflow:global_step/sec: 444.962
INFO:tensorflow:loss = 845093800000.0, step = 101 (0.227 sec)
INFO:tensorflow:global_step/sec: 800.826
INFO:tensorflow:loss = 318829920000.0, step = 201 (0.124 sec)
INFO:tensorflow:global_step/sec: 885.878
INFO:tensorflow:loss = 339961500000.0, step = 301 (0.114 sec)
INFO:tensorflow:global_step/sec: 855.586
INFO:tensorflow:loss = 177534700000.0, step = 401 (0.117 sec)
INFO:tensorflow:global_step/sec: 870.464
INFO:tensorflow:loss = 91458175000.0, step = 501 (0.115 sec)
INFO:tensor

** Create a prediction input function and then use the .predict method off your estimator model to create a list or predictions on your test data. **

In [50]:
pred_input_func = tf.estimator.inputs.pandas_input_fn(x=X_test,
                                                     batch_size=10,
                                                     shuffle=False)

In [65]:
prediction = [i['predictions'] for i in model.predict(pred_input_func)]
prediction

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Tzeentch\AppData\Local\Temp\tmprwo_xlwq\model.ckpt-1000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[array([224817.25], dtype=float32),
 array([269393.3], dtype=float32),
 array([216499.98], dtype=float32),
 array([181187.12], dtype=float32),
 array([247510.55], dtype=float32),
 array([202834.33], dtype=float32),
 array([226565.95], dtype=float32),
 array([205089.67], dtype=float32),
 array([207752.03], dtype=float32),
 array([171796.11], dtype=float32),
 array([205846.64], dtype=float32),
 array([228959.3], dtype=float32),
 array([192418.36], dtype=float32),
 array([176747.22], dtype=float32),
 array([252761.64], dtype=float32),
 array([172112.23], dtype=float32),
 array([201221.2], dtype=float32),
 array([184462.31], dtype=float32),
 array([180924.08], dtype=float32),
 array([220445.83], dtype=float32),
 array([172566.81], dtype=float32),
 array([233917.12], dtype=float32),
 array([215042.39], dtype=float32),
 array([169218.45], dtype=float32),
 array([194439.], dtype=float32),
 array([247361.95], dtype=float32),
 array([189646.44], dtype=float32),
 array([152191.72], dtype=float32

In [63]:
from sklearn.metrics import mean_squared_error

** Calculate the RMSE. You should be able to get around 100,000 RMSE (remember that this is in the same units as the label.) Do this manually or use [sklearn.metrics](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html) **

In [66]:
mean_squared_error(y_test, prediction)**0.5

104584.47755685901

97921.93181985477

# Great Job!